name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '24 4 * * *'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: 准备代码
        uses: actions/checkout@v4

      - name: 安装uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.8.11"
          enable-cache: true

      - name: 准备python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
            
      - name: 安装依赖（含开发工具）
        run: uv sync

      - name: 准备打包文件
        run: |
          mkdir -p dist
          # 复制源代码
          cp -r src dist/
          # 复制依赖配置文件
          cp pyproject.toml dist/
          cp main.py dist/
          cp uv.lock dist/

      - name: 准备打包Docker镜像的环境
        uses: docker/setup-buildx-action@v3

      # 登录到Docker Hub
      - name: 登录Docker Hub
        if: github.event_name != 'pull_request'  # PR时不登录
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建并推送Docker镜像
      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

